export const FOCUS_BOOTH = 'FOCUS_BOOTH';
export const INPUT_SEARCH_KEYWORD = 'INPUT_SEARCH_KEYWORD';
export const COMPLETE_SEARCH_KEYWORD = 'COMPLETE_SEARCH_KEYWORD';
export const CHANGE_MAP_COORD = 'CHANGE_MAP_COORD';
export const CHANGE_BOTTOMSHEET_HEIGHT = 'CHANGE_BOTTOMSHEET_HEIGHT';
export const CHANGE_BOOTH_DATA = 'CHANGE_BOOTH_DATA';
export const CHANGE_FILTER = {
  BRANDS: 'CHANGE_BRANDS_FILTER',
  TAG: 'CHANGE_TAG_FILTER',
};
