export const FOCUS_BOOTH = 'FOCUS_BOOTH';
export const INPUT_SEARCH_KEYWORD = 'INPUT_SEARCH_KEYWORD';
export const CHANGE_MAP_COORD = 'CHANGE_MAP_COORD';
export const CHANGE_BOTTOMSHEET_HEIGHT = 'CHANGE_BOTTOMSHEET_HEIGHT';
export const CHANGE_FILTER = {
  BRAND: 'CHANGE_BRAND_FILTER',
  TAG: 'CHANGE_TAG_FILTER',
};
