export const INPUT_POST_CONTENTS = 'INPUT_POST_CONTENTS';
export const ADD_POST_WRITE_IMAGE = 'ADD_POST_WRITE_IMAGE';
export const TOGGLE_TAG_CHIP = 'TOGGLE_TAG_CHIP';
export const ADD_DIRECT_TAG = 'ADD_DIRECT_TAG';
export const CLEAR_POST_WRITE = 'CLEAR_POST_WRITE';
export const CHANGE_SHARED_SCOPE = 'CHANGE_SHARED_SCOPE';
export const CHANGE_MODIFY_MODE = 'CHANGE_MODIFY_MODE';
export const CHANGE_CUSTOM_TAG = 'CHANGE_CUSTOM_TAG';
