export const OPEN_FILTER_SHEET = 'OPEN_FILTER_SHEET';
export const CLOSE_FILTER_SHEET = 'CLOSE_FILTER_SHEET';
export const CHANGE_FOCUS = 'CHANGE_FOCUS';
export const CHANGE_FILTER = {
  BRAND: 'CHANGE_BRAND_FILTER',
  HEADCOUNT: {
    NUMBER: 'CHANGE_HEADCOUNT_NUMBER_FILTER',
    RELATION: 'CHANGE_HEADCOUNT_RELATION_FILTER',
  },
  POSE: {
    EMOTION: 'CHANGE_EMOTION_POSE_FILTER',
    SITUATION: 'CHANGE_SITUATION_POSE_FILTER',
  },
  FRAME: 'CHANGE_FRAME_FILTER',
};
