export const CHANGE_STARS = 'CHANGE_STARS';
export const CHANGE_TAG_DATA = 'CHANGE_TAG_DATA';
export const ADD_IMAGE = 'ADD_IMAGE';
export const ADD_STORE_DESCRIPTION = 'ADD_STORE_DESCRIPTION';
export const SHOW_PAUSE_MODAL = 'SHOW_PAUSE_MODAL';
export const CLEAR_DATA = 'CLEAR_DATA';
export const CHANGE_TAGS = {
  SPECIFIC: 'CHANGE_TAGS_SPECIFIC',
  RESULT: 'CHANGE_TAGS_RESULT',
};
export const START_UPDATE = 'START_UPDATE';
export const ADD_DELETE_IMAGE = 'ADD_DELETE_IMAGE';
export const CHANGE_DELETE_IMAGE = 'CHANGE_DELETE_IMAGE';
