export const CHANGE_STARS = 'CHANGE_STARS';
export const CHANGE_TAG_DATA = 'CHANGE_TAG_DATA';
export const ADD_IMAGE = 'ADD_IMAGE';
export const ADD_STORE_DESCRIPTION = 'ADD_STORE_DESCRIPTION';
export const SHOW_PAUSE_MODAL = 'SHOW_PAUSE_MODAL';
export const CLEAR_DATA = 'CLEAR_DATA';
